export const categoryConstants = {
  GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
  GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',
  CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',
  GET_BY_SLUG_REQUEST:"GET_BY_SLUG_REQUEST",
  GET_BY_SLUG_SUCCESS:"GET_BY_SLUG_SUCCESS",
  GET_BY_SLUG_FAILURE:"GET_BY_SLUG_FAILURE"
}
